export const Mac_type = ["MacBook", "MacBook Air", "MacBook Pro", "Mac mini", "iMac", "iMac Pro", "Mac Pro", "Mac Studio", "Thunderbolt & Studio Display"];
export const Series = [
    { name: "MacBook (Retina, 12-inch, Early 2015)", type: 'MacBook' },
    { name: "MacBook (Retina, 12-inch, Early 2016)", type: 'MacBook' },
    { name: "MacBook (Retina, 12-inch, 2017)", type: 'MacBook' },

    { name: "11-inch", type: "MacBook Air" },
    { name: "13-inch", type: "MacBook Air" },
    { name: "15-inch", type: "MacBook Air" },

    { name: "13-inch", type: "MacBook Pro" },
    { name: "14-inch", type: "MacBook Pro" },
    { name: "15-inch", type: "MacBook Pro" },
    { name: "16-inch", type: "MacBook Pro" },

    { name: "Mac mini (Late 2012)", type: "Mac mini" },
    { name: "Mac mini-Server (Late 2012)", type: "Mac mini" },
    { name: "Mac mini (Late 2014)", type: "Mac mini" },
    { name: "Mac mini (2018)", type: "Mac mini" },
    { name: "Mac mini (M1, 2020)", type: "Mac mini" },
    { name: "Mac mini (M2, M2 Pro, 2023)", type: "Mac mini" },
    { name: "Mac mini (M4, M4 Pro, 2024)", type: "Mac mini" },

    { name: "21-inch", type: "iMac" },
    { name: "24-inch", type: "iMac" },
    { name: "27-inch", type: "iMac" },

    { name: "iMac Pro (2017)", type: "iMac Pro" },
    { name: "Mac Pro (Late 2013)", type: "Mac Pro" },

    { name: "Mac Pro (2019)", type: "Mac Pro" },
    { name: "Mac Pro (2023)", type: "Mac Pro" },

    { name: "Mac Studio (M1, 2022)", type: "Mac Studio" },
    { name: "Mac Studio (M2, 2023)", type: "Mac Studio" },

    { name: "Apple Cinema Display (without 27-inch)", type: "Thunderbolt & Studio Display" },
    {name:"Apple Thunderbolt Display (without 27-inch)",type: "Thunderbolt & Studio Display"},
    {name:"Pro Display XDR",type: "Thunderbolt & Studio Display"},
    {name:"Studio Display (2022)",type: "Thunderbolt & Studio Display"},
];
export const CategoryArray = [
    //MacBook Air
    { name: "MacBook Air (11-inch, Late 2010)", type: "MacBook Air", series: "11-inch" },
    { name: "MacBook Air (11-inch, Mid 2011)", type: "MacBook Air", series: "11-inch" },
    { name: "MacBook Air (11-inch, Mid 2012)", type: "MacBook Air", series: "11-inch" },
    { name: "MacBook Air (11-inch, Early 2014)", type: "MacBook Air", series: "11-inch" },
    { name: "MacBook Air (11-inch, Early 2015)", type: "MacBook Air", series: "11-inch" },

    { name: "MacBook Air (13-inch, Late 2010)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (13-inch, Mid 2011)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (13-inch, Mid 2012)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (13-inch, Mid 2013)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (13-inch, Early 2014)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (13-inch, Early 2015)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (13-inch, 2017)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (Retina, 13-inch, 2018)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (Retina, 13-inch, 2019)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (Retina, 13-inch, 2020)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (M1,13-inch, 2020)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (M2,13-inch, 2022)", type: "MacBook Air", series: "13-inch" },
    { name: "MacBook Air (M3,13-inch, 2024)", type: "MacBook Air", series: "13-inch" },

    { name: "MacBook Air (15-inch, M2, 2023)", type: "MacBook Air", series: "15-inch" },
    { name: "MacBook Air (15-inch, M3, 2024)", type: "MacBook Air", series: "15-inch" },

    //MacBook Pro
    {name:"MacBook Pro(13 - inch, Mid 2012)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(Retina, 13 - inch, Late 2012)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(Retina, 13 - inch, Early 2013)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(Retina, 13 - inch, Late 2013)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(Retina, 13 - inch, Mid 2014)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(Retina, 13 - inch, Early 2015)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2016, Two Thunderbolt 3 Ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2016, Four Thunderbolt 3 Ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2017, Two Thunderbolt 3 Ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2017, Four Thunderbolt 3 Ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2018, Four Thunderbolt 3 Ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2019, Four Thunderbolt 3 ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2019, Two Thunderbolt 3 ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2020, Two Thunderbolt 3 ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, 2020, Four Thunderbolt 3 ports)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, M1, 2020)",type: "MacBook Pro", series: "13-inch"},
    {name:"MacBook Pro(13 - inch, M2, 2022)",type: "MacBook Pro", series: "13-inch"},

    {name:"MacBook Pro (14-inch, M1, 2021)",type: "MacBook Pro", series: "14-inch"},
    {name:"MacBook Pro (14-inch, M2, 2023)",type: "MacBook Pro", series: "14-inch"},
    {name:"MacBook Pro (14-inch, M3, Nov 2023)",type: "MacBook Pro", series: "14-inch"},
    {name:"MacBook Pro (14-inch, M3 Pro or M3 Max, Nov 2023)",type: "MacBook Pro", series: "14-inch"},
    {name:"MacBook Pro (14-inch, M4, 2024)",type: "MacBook Pro", series: "14-inch"},
    {name:"MacBook Pro (14-inch, M4 Pro or M4 Max, 2024)",type: "MacBook Pro", series: "14-inch"},

    {name:"MacBook Pro (15-inch, 2009-2011)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (15-inch, Mid 2012)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (Retina, 15-inch, Mid 2012)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (Retina, 13-inch, Early 2013)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (Retina, 15-inch, Late 2013)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (Retina, 15-inch, Mid 2014)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (Retina, 15-inch, Mid 2015)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (15-inch, 2016)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (15-inch, 2017)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (15-inch, 2018)",type: "MacBook Pro", series: "15-inch"},
    {name:"MacBook Pro (15-inch, 2019)",type: "MacBook Pro", series: "15-inch"},

    {name:"MacBook Pro (16-inch, 2019)",type: "MacBook Pro", series: "16-inch"},
    {name:"MacBook Pro (16-inch, M1, 2021)",type: "MacBook Pro", series: "16-inch"},
    {name:"MacBook Pro (16-inch, M2, 2023)",type: "MacBook Pro", series: "16-inch"},
    {name:"MacBook Pro (16-inch, M3, Nov 2023)",type: "MacBook Pro", series: "16-inch"},
    {name:"MacBook Pro (16-inch, M4, 2024)",type: "MacBook Pro", series: "16-inch"},

    //iMac
    {name:"iMac (21.5-inch, Late 2012)",type: "iMac", series: "21-inch"},
    {name:"iMac (21.5-inch, Early 2013)",type: "iMac", series: "21-inch"},
    {name:"iMac (21.5-inch, Late 2013)",type: "iMac", series: "21-inch"},
    {name:"iMac (21.5-inch, Mid 2014)",type: "iMac", series: "21-inch"},
    {name:"iMac (21.5-inch, Late 2015)",type: "iMac", series: "21-inch"},
    {name:"iMac (Retina 4K, 21.5-inch, Late 2015)",type: "iMac", series: "21-inch"},
    {name:"iMac (21.5-inch, 2017)",type: "iMac", series: "21-inch"},
    {name:"iMac (Retina 4K, 21.5-inch, 2017)",type: "iMac", series: "21-inch"},
    {name:"iMac (Retina 4K, 21.5-inch, 2019)",type: "iMac", series: "21-inch"},

    {name:"iMac (24-inch, M1, 2021)",type:"iMac",series:"24-inch"},
    {name:"iMac (24-inch, M3, 2023)",type:"iMac",series:"24-inch"},
    {name:"iMac (24-inch, M4, 2024)",type:"iMac",series:"24-inch"},

    {name:"iMac (27-inch, Late 2012)",type:"iMac",series:"27-inch"},
    {name:"iMac (27-inch, Late 2013)",type:"iMac",series:"27-inch"},
    {name:"iMac (Retina 5K, 27-inch, Late 2014)",type:"iMac",series:"27-inch"},
    {name:"iMac (Retina 5K, 27-inch, Mid 2015)",type:"iMac",series:"27-inch"},
    {name:"iMac (Retina 5K, 27-inch, Late 2015)",type:"iMac",series:"27-inch"},
    {name:"iMac (Retina 5K, 27-inch, 2017)",type:"iMac",series:"27-inch"},
    {name:"iMac (Retina 5K, 27-inch, 2019)",type:"iMac",series:"27-inch"},
    {name:"iMac (Retina 5K, 27-inch, 2020)",type:"iMac",series:"27-inch"},
]